# -*- coding: utf-8 -*-
"""Prueba-v1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JAo_XYXjCWLExFWzy5e3nR6nlQ0naB5Z
"""

ubicacion     = (-1,3)
radio_max     = 10.35
tipo_negocio  = 'restaurante'

def main_funcion(ubicacion,radio_max,tipo_negocio):

  limite_superior = ubicacion[0] + radio_max
  limite_inferior = ubicacion[0] - radio_max
  limite_derecho = ubicacion[1] + radio_max
  limite_izquierdo = ubicacion[1] - radio_max

  if tipo_negocio.lower() == 'restaurante' or tipo_negocio.lower() == 'panaderia':
    categoria = 'vital'
  else:
    categoria = 'no vital'

  print("Rango de busqueda: [",limite_inferior,",",limite_derecho,"]x[",limite_superior,",",limite_izquierdo,"]")
  print('Categoría: ', categoria)

main_funcion(ubicacion,radio_max,tipo_negocio)

def main_funcion2(ubicacion,radio_max,tipo_negocio):

  limite_superior = ubicacion[0] + radio_max
  limite_inferior = ubicacion[0] - radio_max
  limite_derecho = ubicacion[1] + radio_max
  limite_izquierdo = ubicacion[1] - radio_max

  if tipo_negocio.lower() == 'restaurante' or tipo_negocio.lower() == 'panaderia':
    categoria = 'vital'
  else:
    categoria = 'no vital'
  return limite_inferior,limite_derecho,limite_superior,limite_izquierdo,categoria

limite_inferior,limite_derecho,limite_superior,limite_izquierdo,categoria = main_funcion2(ubicacion,radio_max,tipo_negocio)